### ISSUE TITLE
Environment config not working

### ISSUE THREAD

**Issue by Wishdream** [codetheweb/aoede#24]
I'm currently using the docker-compose given via portainer
and provides the following error:
```log
Couldn't read config
Missing field: 'DISCORD_TOKEN'
```

All my environment vars are set and just following the provided docker-compose file:
```yaml
version: '3.4'

services:
  aoede:
    image: codetheweb/aoede
    restart: always
    volumes:
      - ./aoede:/data
    environment:
      - DISCORD_TOKEN=discord.token.here
      - SPOTIFY_USERNAME=spotitest
      - SPOTIFY_PASSWORD=notarealpassword
      - DISCORD_USER_ID=targeteduserIDhere
```

I think it's trying to read the config.toml where it shouldn't exist or somehow got bundled with the docker image
